"""add weather_search identity constraint

Revision ID: 08cac97df86c
Revises: 10e6475c2f6f
Create Date: 2026-06-02 21:40:38.339460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cac97df86c'
down_revision: Union[str, None] = '10e6475c2f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_weather_search_identity', 'weather_searches', ['location', 'units', 'start_date', 'end_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weather_search_identity', 'weather_searches', type_='unique')
    # ### end Alembic commands ###
